tables = {
    "P3980": {
        "name": "Aktywni zawodowo wg płci i wieku",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": "2010-2024",
        "level": "Regiony (NUTS 2)",
        "last_update": "26.02.2025",
    },
    "P3969": {
        "name": "Aktywność ekonomiczna ludności wg miejsca zamieszkania",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": "2010-2024",
        "level": "Regiony (NUTS 2)",
        "last_update": "26.02.2025",
    },
    "P3983": {
        "name": "Odsetek ludności w wieku 15-64 lata wg poziomu wykształcenia",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": "2010-2024",
        "level": "Regiony (NUTS 2)",
        "last_update": "26.02.2025",
    },
    "P3970": {
        "name": "Pracujący wg płci, wymiaru czasu pracy i sekcji PKD",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": "2010-2024",
        "level": "Regiony (NUTS 2)",
        "last_update": "26.02.2025",
    },
    "P3974": {
        "name": "Współczynnik aktywności zawodowej wg płci i wieku",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": "2010-2024",
        "level": "Regiony (NUTS 2)",
        "last_update": "26.02.2025",
    },
    "P3981": {
        "name": "Współczynnik aktywności zawodowej według poziomu wykształcenia",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": "2010-2024",
        "level": "Regiony (NUTS 2)",
        "last_update": "26.02.2025",
    },
    "P1944": {
        "name": "Bezrobotni zarejestrowani wg płci w gminach",
        "category": "RYNEK PRACY (K4)",
        "group": "BEZROBOCIE REJESTROWANE (G12)",
        "years": "2003-2024",
        "level": "Gminy",
        "last_update": "27.02.2025",
    },
    "P1365": {
        "name": "Oferty pracy wg grup osób",
        "category": "RYNEK PRACY (K4)",
        "group": "BEZROBOCIE REJESTROWANE (G12)",
        "years": "1999-2024",
        "level": "Powiaty",
        "last_update": "11.02.2025",
    },
    "P3567": {
        "name": "Odsetek bezrobotnych zarejestrowanych wg poziomu wykształcenia",
        "category": "RYNEK PRACY (K4)",
        "group": "BEZROBOCIE REJESTROWANE (G12)",
        "years": "2003-2024",
        "level": "Powiaty",
        "last_update": "11.02.2025",
    },
    "P3591": {
        "name": "Odsetek bezrobotnych zarejestrowanych wg grup wieku",
        "category": "RYNEK PRACY (K4)",
        "group": "BEZROBOCIE REJESTROWANE (G12)",
        "years": "2010-2024",
        "level": "Powiaty",
        "last_update": "11.02.2025",
    },
    "P1946": {
        "name": "Bezrobotni zarejestrowani wg wieku i płci",
        "category": "RYNEK PRACY (K4)",
        "group": "BEZROBOCIE REJESTROWANE (G12)",
        "years": "2000-2024",
        "level": "Powiaty",
        "last_update": "11.02.2025",
    },
}
