tables_metadata = {
    "3980": {
        "name": "Aktywni zawodowo wg płci i wieku",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": list(range(2015, 2025)),
        "regions": ["Polska", "Wielkopolskie", "Mazowieckie", "Zachodniopomorskie"],
        "age_range": "poniżej 45 lat",
        "table_id": {"CTAB": "112225", "CREL": "110345"},
        "alias": "akt_wg_plci_wieku",
    },
    "3969": {
        "name": "Aktywność ekonomiczna ludności wg miejsca zamieszkania",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": list(range(2015, 2025)),
        "regions": ["Polska", "Wielkopolskie", "Mazowieckie", "Zachodniopomorskie"],
        "age_range": "poniżej 45 lat",
        "table_id": {"CTAB": "113151", "CREL": "113039"},
        "alias": "akt_wg_zamieszkania",
    },
    "3983": {
        "name": "Odsetek ludności w wieku 15-64 lata wg poziomu wykształcenia",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": list(range(2015, 2025)),
        "regions": ["Polska", "Wielkopolskie", "Mazowieckie", "Zachodniopomorskie"],
        "age_range": "poniżej 45 lat",
        "table_id": {"CTAB": "113528", "CREL": "113533"},
        "alias": "ods_ludnosc_wg_wyksztalcenia",
    },
    "3970": {
        "name": "Pracujący wg płci, wymiaru czasu pracy i sekcji PKD",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": list(range(2015, 2025)),
        "regions": ["Polska", "Wielkopolskie", "Mazowieckie", "Zachodniopomorskie"],
        "age_range": "poniżej 45 lat",
        "table_id": {"CTAB": "114136", "CREL": "114457"},
        "alias": "pracujacy_wg_plci_pkd",
    },
    "3974": {
        "name": "Współczynnik aktywności zawodowej wg płci i wieku",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": list(range(2015, 2025)),
        "regions": ["Polska", "Wielkopolskie", "Mazowieckie", "Zachodniopomorskie"],
        "age_range": "poniżej 45 lat",
        "table_id": {"CTAB": "115448", "CREL": "115500"},
        "alias": "wspolczynnik_akt_wg_plci_wieku",
    },
    "3981": {
        "name": "Współczynnik aktywności zawodowej według poziomu wykształcenia",
        "category": "RYNEK PRACY (K4)",
        "group": "AKTYWNOŚĆ EKONOMICZNA LUDNOŚCI W WIEKU 15-89 LAT WEDŁUG BAEL (DANE KWARTALNE) (G623)",
        "years": list(range(2015, 2025)),
        "regions": ["Polska", "Wielkopolskie", "Mazowieckie", "Zachodniopomorskie"],
        "age_range": "poniżej 45 lat",
        "table_id": {"CTAB": "115711", "CREL": "115714"},
        "alias": "akt_wg_wyksztalcenia",
    },
    "1944": {
        "name": "Bezrobotni zarejestrowani wg płci w gminach",
        "category": "RYNEK PRACY (K4)",
        "group": "BEZROBOCIE REJESTROWANE (G12)",
        "years": list(range(2015, 2025)),
        "regions": ["Polska", "Wielkopolskie", "Mazowieckie", "Zachodniopomorskie"],
        "age_range": "poniżej 45 lat",
        "table_id": {"CTAB": "120123", "CREL": "120125"},
        "alias": "bezr_wg_plci_gminy",
    },
    "1365": {
        "name": "Oferty pracy wg grup osób",
        "category": "RYNEK PRACY (K4)",
        "group": "BEZROBOCIE REJESTROWANE (G12)",
        "years": list(range(2015, 2025)),
        "regions": ["Polska", "Wielkopolskie", "Mazowieckie", "Zachodniopomorskie"],
        "age_range": "poniżej 45 lat",
        "table_id": {"CTAB": "120303", "CREL": "120305"},
        "alias": "oferty_pracy_grupy",
    },
    "3567": {
        "name": "Odsetek bezrobotnych zarejestrowanych wg poziomu wykształcenia",
        "category": "RYNEK PRACY (K4)",
        "group": "BEZROBOCIE REJESTROWANE (G12)",
        "years": list(range(2015, 2025)),
        "regions": ["Polska", "Wielkopolskie", "Mazowieckie", "Zachodniopomorskie"],
        "age_range": "poniżej 45 lat",
        "table_id": {"CTAB": "120417", "CREL": "120418"},
        "alias": "ods_bezr_wg_wyksztalcenia",
    },
    "3591": {
        "name": "Odsetek bezrobotnych zarejestrowanych wg grup wieku",
        "category": "RYNEK PRACY (K4)",
        "group": "BEZROBOCIE REJESTROWANE (G12)",
        "years": list(range(2015, 2025)),
        "regions": ["Polska", "Wielkopolskie", "Mazowieckie", "Zachodniopomorskie"],
        "age_range": "poniżej 45 lat",
        "table_id": {"CTAB": "120542", "CREL": "120544"},
        "alias": "ods_bezr_wg_wieku",
    },
    "1946": {
        "name": "Bezrobotni zarejestrowani wg wieku i płci",
        "category": "RYNEK PRACY (K4)",
        "group": "BEZROBOCIE REJESTROWANE (G12)",
        "years": list(range(2015, 2025)),
        "regions": ["Polska", "Wielkopolskie", "Mazowieckie", "Zachodniopomorskie"],
        "age_range": "poniżej 45 lat",
        "table_id": {"CTAB": "120123", "CREL": "120759"},
        "alias": "bezr_wg_wieku_plci",
    },
}
